name: Actions_GSI

on:
  workflow_dispatch:
    inputs:
      GSI:
        description: 'GSI(y or n)'
        required: true
        default: 'y'
      ROM_URL:
        description: 'Rom_url'
        required: true
        default: 'https://bigota.d.miui.com/21.4.22/miui_VIOLET_21.4.22_904fe2ee16_10.0.zip'
      ROM_device:
        description: 'Rom_device'
        required: true
        default: 'Redmi_Note7_Pro'
      OS_TYPE:
        description: 'OS_type'
        required: true
        default: 'MIUI'
      ROM_NAME:
        description: 'Rom_name'
        required: true
        default: 'GSI_VIOLET_21.4.22_10.0.zip'
      GSI_TYPE:
        description: 'ab or aonly'
        required: true
        default: 'ab'
      Ali_Upload:
        description: 'Upload_Ali(y or n)'
        required: true
        default: 'y'
      Onedrive:
        description: 'Upload_od(y or n)'
        required: true
        default: 'y'
      wenshushu:
        description: 'Upload_wenshushu(y or n)'
        required: true
        default: 'n'
      cloud189: 
        description: 'Upload_tianyiyunpan(y or n)'
        required: true
        default: 'y'
      
env: 
  TZ: Asia/Shanghai
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  ROM_device: ${{ github.event.inputs.ROM_device }}
  ROM_NAME: ${{ github.event.inputs.ROM_NAME }}
  GSI_TYPE: ${{ github.event.inputs.GSI_TYPE }}
  OS_TYPE: ${{ github.event.inputs.OS_TYPE }}
  ali: ${{ secrets.ALI }}
  Onedrive: ${{ github.event.inputs.Onedrive }}
  GSI: ${{ github.event.inputs.GSI }}
  OD: ${{ secrets.PASSWD }}
  wenshushu: ${{ github.event.inputs.wenshushu }}
  Ali_Upload: ${{ github.event.inputs.Ali_Upload }} 
  cloud: ${{ github.event.inputs.cloud189 }}
  cloud189: ${{ secrets.CLOUD189 }}
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
        
      - name: Execute GSI.sh
        run: |
          if [ "$GSI" = y ];then
              chmod +x GSI.sh && ./GSI.sh
          else
             echo -e "\e[1;32m未选择GSI..\e[0m"
          fi
          
      - name: Upload onedrive
        run: |
          if [ "$Onedrive" = y ] && [ -e $GITHUB_WORKSPACE/config.zip];then
              chmod +x Upload/Upload_OneDrive.sh && ./Upload/Upload_OneDrive.sh
          else
             echo -e "\e[1;32m你没有选择上传到OneDrive或者配置文件不存在哦,跳过上传...\e[0m"
          fi
          
      - name: Upload aliyunpan
        run: | 
          if [ "$Ali_Upload" = y ] && [ $ali ];then
              chmod +x Upload/Upload_Aliyunpan.sh && ./Upload/Upload_Aliyunpan.sh
          else
              echo -e "\e[1;32m你没有选择上传到阿里云盘哦或者没有添加refresh_token哦,跳过上传...\e[0m"
          fi
          
      - name: Upload wenshushu
        run: |
          if [ "$wenshushu" = y ];then
              chmod +x Upload/Upload_wenshushu.sh && ./Upload/Upload_wenshushu.sh
          else
              echo -e "\e[1;32m你没有选择上传到文叔叔哦,跳过上传...\e[0m"
          fi
          
      - name: Upload tianyiyunpan
        run: |
          if [ "$cloud" = y ] && [ $cloud189 ];then
              chmod +x Upload/Upload_cloud189.sh && ./Upload/Upload_cloud189.sh
          else
              echo -e "\e[1;32m你没有选择上传到天翼云盘,或者未指定账号和密码哦，跳过上传,\e[0m"
          fi

          
           
