name: text

on:
  workflow_dispatch:
    inputs:
      GSI:
        description: 'GSI(y or n)'
        required: true
        default: 'y'
      ROM_URL:
        description: 'Rom_url'
        required: true
        default: 'https://bigota.d.miui.com/21.4.22/miui_VIOLET_21.4.22_904fe2ee16_10.0.zip'
      ROM_device:
        description: 'Rom_device'
        required: true
        default: 'Redmi_Note7_Pro'
      OS_TYPE:
        description: 'OS_type'
        required: true
        default: 'MIUI'
      ROM_NAME:
        description: 'Rom_name'
        required: true
        default: 'GSI_VIOLET_21.4.22_10.0.zip'
      GSI_TYPE:
        description: 'ab or aonly'
        required: true
        default: 'ab'
      Ali_Upload:
        description: 'Upload_Ali(y or n)'
        required: true
        default: 'y'
      Onedrive:
        description: 'Upload_od(y or n)'
        required: true
        default: 'y'
      wenshushu:
        description: 'Upload_wenshushu(y or n)'
        required: true
        default: 'y'
      
      
env: 
  TZ: Asia/Shanghai
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  ROM_device: ${{ github.event.inputs.ROM_device }}
  ROM_NAME: ${{ github.event.inputs.ROM_NAME }}
  GSI_TYPE: ${{ github.event.inputs.GSI_TYPE }}
  OS_TYPE: ${{ github.event.inputs.OS_TYPE }}
  ali: ${{ secrets.ALI }}
  Onedrive: ${{ github.event.inputs.Onedrive }}
  GSI: ${{ github.event.inputs.GSI }}
  OD: ${{ secrets.PASSWD }}
  wenshushu: ${{ github.event.wenshushu }}
  Ali_Upload: ${{ github.event.Ali_Upload}} 
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
        
      - name: Execute GSI.sh
        run: |
          if [ "$GSI" = y ];then
              chmod +x GSI.sh && ./GSI.sh
          else
             echo -e "\e[1;32m未选择GSI\e[0m"
          fi
          
      - name: uUpload onedrive
        run: |
          if [ "$Onedrive" = y ];then
              chmod +x Upload/Upload_OneDrive.sh && ./Upload/Upload_OneDrive.sh
          else
             echo -e "\e[1;32m你没有选择上传到OneDrive哦,跳过上传\e[0m"
          fi
          chmod +x Upload/Upload_Onedrive_rclone.sh && ./Upload/Upload_Onedrive_rclone.sh
          
          
      - name: Upload aliyunpan
        run: | 
          if [ "$Ali_Upload" = y ];then
              chmod +x Upload/Upload_Aliyunpan.sh && ./Upload/Upload_Aliyunpan.sh
          else
              echo -e "\e[1;32m你没有选择上传到阿里云盘哦,跳过上传\e[0m"
          fi
          
      - name: Upload wenshushu
        run: |
          if [ "$wenshushu" = y ];then
              chmod +x Upload/Upload_wenshushu.sh && ./Upload/Upload_wenshushu.sh
          else
              echo -e "\e[1;32m你没有选择上传到文叔叔哦,跳过上传\e[0m"
          fi

          
           
