name: text

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Rom_url'
        required: true
        default: 'https://bigota.d.miui.com/21.4.22/miui_VIOLET_21.4.22_904fe2ee16_10.0.zip'
      ROM_device:
        description: 'Rom_device'
        required: true
        default: 'Redmi_Note7_Pro'
      OS_TYPE:
        description: 'OS_type'
        required: true
        default: 'MIUI'
      ROM_NAME:
        description: 'Rom_name'
        required: true
        default: 'GSI_VIOLET_21.4.22_10.0.zip'
      GSI_TYPE:
        description: 'ab or aonly'
        required: true
        default: 'ab'
      Ali_Upload:
        description: 'Upload_Ali'
        required: true
        default: 'y/n'
      Onedrive:
        description: 'Upload_od'
        required: true
        default: 'y/n'
      GSI:
        description: 'GSI'
        required: true
        default: 'y/n'
      
      
env: 
  TZ: Asia/Shanghai
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  ROM_device: ${{ github.event.inputs.ROM_device }}
  ROM_NAME: ${{ github.event.inputs.ROM_NAME }}
  GSI_TYPE: ${{ github.event.inputs.GSI_TYPE }}
  OS_TYPE: ${{ github.event.inputs.OS_TYPE }}
  ali: ${{ secrets.ALI }}
  Ali_Upload: ${{ github.event.inputs.Ali_Upload }}
  Onedrive: ${{ github.event.inputs.Onedrive }}
  GSI: ${{ github.event.inputs.GSI }}
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
        
      - name: Execute GSI.sh
        if: ${{ github.event.inputs.GSI }} == 'y'
        run: |
          chmod +x GSI.sh && ./GSI.sh
          
      - name: upload onedrive
        if: ${{ github.event.inputs.Onedrive }} == 'y'
        run: |
          chmod +x Upload/Upload_OneDrive.sh && ./Upload_OneDrive.sh
        
      - name: upload aliyunpan
        if: ${{ github.event.inputs.Ali_Upload }} == 'y'
        run: |  
          chmod +x Upload/Upload_Aliyunpan.sh && ./Upload_Aliyunpan.sh
            
