name: text

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'GSI'
        required: true
        default: ''
        
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
