name: text

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Rom_url'
        required: true
        default: 'https://bigota.d.miui.com/21.4.22/miui_VIOLET_21.4.22_904fe2ee16_10.0.zip'
      ROM_device:
        description: 'Rom_device'
        required: true
        default: 'Redmi_Note7_Pro'
      OS_TYPE:
        description: 'OS_type'
        required: true
        default: 'MIUI'
      ROM_NAME:
        description: 'Rom_name'
        required: true
        default: 'GSI_VIOLET_21.4.22_10.0.zip'
      GSI_TYPE:
        description: 'ab or aonly'
        required: true
        default: 'ab'
      
env: 
  TZ: Asia/Shanghai
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  ROM_device: ${{ github.event.inputs.ROM_device }}
  ROM_NAME: ${{ github.event.inputs.ROM_NAME }}
  GSI_TYPE: ${{ github.event.inputs.GSI_TYPE }}
  OS_TYPE: ${{ github.event.inputs.OS_TYPE }}
  ali: ${{ secrets.ALI }}
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
        
      - name: Execute GSI.sh
        run: |
          chmod +x GSI.sh && ./GSI.sh
          
      - name: GSI
        run: |
          cd ./ErfanGSIs
          sudo bash ./url2GSI.sh --$GSI_TYPE $ROM_URL $OS_TYPE
          echo "------------ Compressed output file ------------ "
          cd $GITHUB_WORKSPACE/ErfanGSIs
          mkdir $ROM_device
          cd $ROM_device
          zip -q -r $ROM_NAME $GITHUB_WORKSPACE/ErfanGSIs/output
      
      - name: upload aliyunpan
        run: |
          cd $GITHUB_WORKSPACE/ErfanGSIs
          sudo chmod +x aliyunpan.sh && sudo sh aliyunpan.sh

      
