name: text

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Rom_url'
        required: true
        default: 'https://bigota.d.miui.com/21.4.22/miui_VIOLET_21.4.22_904fe2ee16_10.0.zip'
      ROM_device:
        description: 'Rom_device'
        required: true
        default: 'Redmi Note7 Pro'
      OS_TYPE:
        description: 'OS_type'
        required: true
        default: 'MIUI'
      ROM_NAME:
        description: 'Rom_name'
        required: true
        default: 'GSI_VIOLET_21.4.22_10.0.zip'
      
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
        
      - name: Execute GSI.sh
        run: |
          chmod +x GSI.sh && ./GSI.sh
          
      - name: GSI
        run: |
          cd ./ErfanGSIs
          sudo bash ./url2GSI.sh ${{ github.event.inputs.ROM_URL }} MIUI

      
