name: text

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'GSI'
        required: true
        default: ''
        
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main
        
      - name: Execute GSI.sh
        run: |
          chmod +x GSI.sh && ./GSI.
          
      - name: GSI
        run: |
          ./url2GSI.sh https://bigota.d.miui.com/21.4.22/miui_VIOLET_21.4.22_904fe2ee16_10.0.zip MIUI

      
